### ISSUE TITLE
Requests for gulp-cache, gulp-del, a gulp build task, and font compression.  Update off of combine-media-queries

### ISSUE THREAD

**Issue by rooksstrife** [steelydylan/gulp-generator#4]
If you could add the functionality of only recompressing if needed with gulp-cache (images).
Also, to have a gulp build that builds everything out sass/js/image tasks and clears out the specified build folder.

**Comment by rooksstrife** [comment]
Also - great work!

**Comment by rooksstrife** [comment]
The cache one should be easy.  Similar to Quench - http://quenchjs.com/

**Comment by rooksstrife** [comment]
Also, gulp-combine-media-queries does not work with new node.  It hasn't been updated for a year.  I suggest moving to https://www.npmjs.com/package/gulp-merge-media-queries.  This works.  Also, add in log - 
.pipe(mmq({
                log: true
            }))

**Comment by steelydylan** [comment]
Hi rooksstrife!!
Thank you for your advice
I'll add "gulp-cache, gulp-del, gulp-merge-media-queries" ASAP
I'll tell you, when I have done it :)

**Comment by rooksstrife** [comment]
Cool thanks.

**Comment by steelydylan** [comment]
I just updated.  you can use "gulp-cache" and "gulp-merge-media-queries" now.
but I'd like to know what purpose you want to use "gulp-del". you wanna use it for deleting the folder where unoptimized images exist?
and "gulp-generator" already have the task where you can watch and execute "css/html/js" tasks at once, do you still need the function for executing those tasks?
