### ISSUE TITLE
Typescript Support.

### ISSUE THREAD

**Issue by ghost** [steelydylan/gulp-generator#7]
It would be nice to have this.

**Comment by ghost** [comment]
Yep, sorry, i saw it later. It is already there, but altJs doesn't explain it.  And there is something wrong on select box.
![untitled-1](https://cloud.githubusercontent.com/assets/1254613/14229870/86f95bf8-f94a-11e5-8ccc-986fec711530.jpg)

**Comment by steelydylan** [comment]
Hi atilkan !!
thank you for letting me know.
I'm using chrome but I haven't encountered the same problem
I'll check it via other browsers
thank you very much

**Comment by ghost** [comment]
I guess, i've send that screenshot from windows/chrome. It works ok on mac/chrome.
